name: Tests

on:
  - push
  - pull_request

permissions:
  contents: read

jobs:
  phpunit:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: postgresql://symfony:ChangeMe@localhost:5432/app?serverVersion=11&charset=utf8
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: laravel
          POSTGRES_PASSWORD: VerySecretPassword
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
      - uses: actions/checkout@v3
      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Install DB
        run: php artisan migrate:fresh -n --env=test
      - name: PhpUnit functional tests
        run: php vendor/bin/phpunit

